In [10]:
import os
path = '/content/drive/MyDrive/a/KaggleV2-May-2016.csv'

In [11]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/a/KaggleV2-May-2016.csv')

In [12]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [14]:
df.head(10)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
5,9.598513e+13,5626772,F,2016-04-27T08:36:51Z,2016-04-29T00:00:00Z,76,REPÚBLICA,0,1,0,0,0,0,No
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,Yes
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,Yes
8,5.639473e+13,5638447,F,2016-04-29T08:02:16Z,2016-04-29T00:00:00Z,21,ANDORINHAS,0,0,0,0,0,0,No
9,7.812456e+13,5629123,F,2016-04-27T12:48:25Z,2016-04-29T00:00:00Z,19,CONQUISTA,0,0,0,0,0,0,No

In [15]:
df.shape

(110527, 14)

In [16]:
df.columns

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='object')

In [17]:
df.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [21]:
df = df.drop_duplicates()

In [22]:
df.columns = df.columns.str.lower()

In [23]:
df.head()

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [25]:
df.columns = df.columns.str.upper()
df.head()

,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [51]:
df.columns = df.columns.str.lower().str.replace("", " ")
print(df.columns)

Index([' p a t i e n t i d ', ' a p p o i n t m e n t i d ', ' g e n d e r ',
       ' s c h e d u l e d d a y ', ' a p p o i n t m e n t d a y ', ' a g e ',
       ' n e i g h b o u r h o o d ', ' s c h o l a r s h i p ',
       ' h i p e r t e n s i o n ', ' d i a b e t e s ',
       ' a l c o h o l i s m ', ' h a n d c a p ', ' s m s _ r e c e i v e d ',
       ' n o - s h o w '],
      dtype='object')

In [52]:
df.head()

,p a t i e n t i d,a p p o i n t m e n t i d,g e n d e r,s c h e d u l e d d a y,a p p o i n t m e n t d a y,a g e,n e i g h b o u r h o o d,s c h o l a r s h i p,h i p e r t e n s i o n,d i a b e t e s,a l c o h o l i s m,h a n d c a p,s m s _ r e c e i v e d,n o - s h o w
0,1,5642903,F,29-04-2016,29-04-2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,2,5642503,M,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,3,5642549,F,29-04-2016,29-04-2016,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,4,5642828,F,29-04-2016,29-04-2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,5,5642494,F,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [55]:
df.columns = df.columns.str.lower().str.replace(" ", "")
print(df.columns)
df.head()

Index(['patientid', 'appointmentid', 'gender', 'scheduledday',
       'appointmentday', 'age', 'neighbourhood', 'scholarship', 'hipertension',
       'diabetes', 'alcoholism', 'handcap', 'sms_received', 'no-show'],
      dtype='object')

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no-show
0,1,5642903,F,29-04-2016,29-04-2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,2,5642503,M,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,3,5642549,F,29-04-2016,29-04-2016,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,4,5642828,F,29-04-2016,29-04-2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,5,5642494,F,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [60]:
df.columns = df.columns.str.upper()
df.head()

,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,1,5642903,F,2016-04-29,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,2,5642503,M,2016-04-29,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,3,5642549,F,2016-04-29,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,4,5642828,F,2016-04-29,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,5,5642494,F,2016-04-29,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [56]:
df.dtypes

patientid          int64
appointmentid      int64
gender            object
scheduledday      object
appointmentday    object
age                int64
neighbourhood     object
scholarship        int64
hipertension       int64
diabetes           int64
alcoholism         int64
handcap            int64
sms_received       int64
no-show           object
dtype: object

In [58]:
df["SCHEDULEDDAY"] = pd.to_datetime(df["SCHEDULEDDAY"])
df["APPOINTMENTDAY"] = pd.to_datetime(df["APPOINTMENTDAY"])

/tmp/ipykernel_6406/397273232.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["scheduledday"] = pd.to_datetime(df["scheduledday"])
/tmp/ipykernel_6406/397273232.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["appointmentday"] = pd.to_datetime(df["appointmentday"])

PATIENTID                     float64
APPOINTMENTID                   int64
GENDER                         object
SCHEDULEDDAY      datetime64[ns, UTC]
APPOINTMENTDAY    datetime64[ns, UTC]
AGE                             int64
NEIGHBOURHOOD                  object
SCHOLARSHIP                     int64
HIPERTENSION                    int64
DIABETES                        int64
ALCOHOLISM                      int64
HANDCAP                         int64
SMS_RECEIVED                    int64
NO-SHOW                        object
dtype: object

In [33]:
df["SCHEDULEDDAY"] = pd.to_datetime(df["SCHEDULEDDAY"]).dt.strftime("%d-%m-%Y")
df["APPOINTMENTDAY"] = pd.to_datetime(df["APPOINTMENTDAY"]).dt.strftime("%d-%m-%Y")
df.head()

/tmp/ipykernel_6406/3620283871.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["SCHEDULEDDAY"] = pd.to_datetime(df["SCHEDULEDDAY"]).dt.strftime("%d-%m-%Y")
/tmp/ipykernel_6406/3620283871.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["APPOINTMENTDAY"] = pd.to_datetime(df["APPOINTMENTDAY"]).dt.strftime("%d-%m-%Y")

,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,2.987250e+13,5642903,F,29-04-2016,29-04-2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,29-04-2016,29-04-2016,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,29-04-2016,29-04-2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [34]:
df.dtypes

PATIENTID         float64
APPOINTMENTID       int64
GENDER             object
SCHEDULEDDAY       object
APPOINTMENTDAY     object
AGE                 int64
NEIGHBOURHOOD      object
SCHOLARSHIP         int64
HIPERTENSION        int64
DIABETES            int64
ALCOHOLISM          int64
HANDCAP             int64
SMS_RECEIVED        int64
NO-SHOW            object
dtype: object

In [36]:
df["gender"].value_counts()

KeyError: 'gender'

In [37]:
df["GENDER"].value_counts()

GENDER
F    71840
M    38687
Name: count, dtype: int64

In [38]:
df["NO-SHOW"].value_counts()

NO-SHOW
No     88208
Yes    22319
Name: count, dtype: int64

In [39]:
df.head()

,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,2.987250e+13,5642903,F,29-04-2016,29-04-2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,29-04-2016,29-04-2016,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,29-04-2016,29-04-2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [42]:
df["PATIENTID"] = df["PATIENTID"].astype(int)

In [43]:
df["PATIENTID"] = range(1, len(df) + 1)

In [46]:
df.head()

,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,1,5642903,F,29-04-2016,29-04-2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,2,5642503,M,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,3,5642549,F,29-04-2016,29-04-2016,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,4,5642828,F,29-04-2016,29-04-2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,5,5642494,F,29-04-2016,29-04-2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PATIENTID       110527 non-null  int64
 1   APPOINTMENTID   110527 non-null  int64
 2   GENDER          110527 non-null  object
 3   SCHEDULEDDAY    110527 non-null  object
 4   APPOINTMENTDAY  110527 non-null  object
 5   AGE             110527 non-null  int64
 6   NEIGHBOURHOOD   110527 non-null  object
 7   SCHOLARSHIP     110527 non-null  int64
 8   HIPERTENSION    110527 non-null  int64
 9   DIABETES        110527 non-null  int64
 10  ALCOHOLISM      110527 non-null  int64
 11  HANDCAP         110527 non-null  int64
 12  SMS_RECEIVED    110527 non-null  int64
 13  NO-SHOW         110527 non-null  object
dtypes: int64(9), object(5)
memory usage: 11.8+ MB

In [61]:
df.to_csv('/content/drive/MyDrive/a/medical_appointment_cleaned.csv', index=False)